### ISSUE TITLE
Not logged in cart not working

### ISSUE THREAD

**Issue by bighitbiker3** [bighitbiker3/3BlondesAndJason#72]
@PaytonHenson I keep getting this error after merging it - 

```
angular.js:13920 TypeError: Cannot read property 'then' of undefined
    at Scope.scope.addToCart (product.addToCart.js:16)
```

I'll work on it

**Comment by bighitbiker3** [comment]
The issue looks to be in here @PaytonHenson 

```
    ProductListFactory.addProduct = function(product, quantity) {
    $rootScope.cart = $rootScope.cart || {};
    AuthService.getLoggedInUser()
    .then(user => {
      if (!user) {
        $rootScope.cart[product.id] = [product, quantity];
      }
      else {
        return $http.post('/api/me/cart/' + product.id, {quantity: quantity})
      }
    })
        .then((...args) => {
      if (args[0]) return args[0].data;
    })
    }
```

If there is `!user` the factory function doesn't return a promise...meaning you can't `.then()` off it

**Comment by bighitbiker3** [comment]
Weird...i'm even getting the error with a user....

**Comment by bighitbiker3** [comment]
Okay got it...it needed a return on the `AuthServive` function...but the no user cart isn't persisting with cookies.  On page refresh it resets. We need to get it to persist with the cookie sessionId.

**Comment by flyingdutchnick** [comment]
We could also store the userId and cart data on localStorage: https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API

**Comment by bighitbiker3** [comment]
Thanks Nick went the session storage route in that link.  Feel free to check it in the pull request
